# Relatorio de Análise 8

## Identificando e removendo Outliers

In [ ]:
%matplotlib
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('figure', figsize = (14, 6))

In [42]:
dados = pd.read_csv('dados/aluguel_residencial.csv', sep = ';')

In [43]:
dados.boxplot(['Valor'])

In [44]:
dados[dados['Valor'] >= 500000]

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
826,Conjunto Comercial/Sala,Barra da Tijuca,0,0,0,5124,614000.0,NaN,NaN,119.83,Apartamento
884,Conjunto Comercial/Sala,Botafogo,0,56,0,4235,529375.0,114599.0,34345.0,125.00,Apartamento
1163,Conjunto Comercial/Sala,Cidade Nova,0,47,0,7357,514990.0,166709.0,14787.0,70.00,Apartamento
2722,Conjunto Comercial/Sala,Centro,0,15,0,5666,530000.0,1.0,1.0,93.54,Apartamento
2994,Prédio Inteiro,Barra da Tijuca,0,40,0,7500,600000.0,162000.0,13350.0,80.00,Apartamento
4595,Galpão/Depósito/Armazém,Irajá,0,5,0,1100,15000000.0,NaN,1000.0,13636.36,Apartamento
4628,Prédio Inteiro,Centro,0,0,0,6986,560000.0,NaN,NaN,80.16,Apartamento
5565,Conjunto Comercial/Sala,Centro,0,30,0,4940,612550.0,128440.0,NaN,124.00,Apartamento
5592,Prédio Inteiro,Jacarepaguá,0,15,0,1200,120000000.0,NaN,10000.0,100000.00,Apartamento
8067,Prédio Inteiro,Centro,0,90,0,7774,505310.0,NaN,NaN,65.00,Apartamento
8377,Conjunto Comercial/Sala,Centro,0,1,0,40,900700.0,1050.0,120.0,22517.50,Apartamento
10665,Conjunto Comercial/Sala,Cidade Nova,0,80,0,9600,576000.0,130020.0,NaN,60.00,Apartamento
11712,Apartamento,Barra da Tijuca,1,1,0,65,600000.0,980.0,120.0,9230.77,Apartamento
12262,Conjunto Comercial/Sala,Centro,0,2,0,545,627394.0,13093.0,3818.0,1151.18,Apartamento
13041,Prédio Inteiro,Centro,0,0,0,7000,530000.0,NaN,NaN,75.71,Apartamento
15026,Prédio Inteiro,Centro,0,70,0,11002,770140.0,162500.0,NaN,70.00,Apartamento
15387,Conjunto Comercial/Sala,Centro,0,27,0,4442,546840.0,115492.0,NaN,123.11,Apartamento
15535,Prédio Inteiro,Barra da Tijuca,0,90,0,4000,650000.0,NaN,NaN,162.50,Apartamento
15569,Prédio Inteiro,Centro,0,48,0,10448,783600.0,177616.0,36456.0,75.00,Apartamento
16206,Casa de Condomínio,Freguesia (Jacarepaguá),4,2,3,163,800000.0,900.0,NaN,4907.98,Casa
16325,Prédio Inteiro,Barra da Tijuca,0,90,0,5130,500000.0,NaN,27000.0,97.47,Apartamento
16553,Conjunto Comercial/Sala,Glória,0,40,0,4659,605670.0,152256.0,NaN,130.00,Apartamento
17740,Galpão/Depósito/Armazém,Centro,0,83,0,34677,898134.0,NaN,NaN,25.90,Apartamento
18094,Prédio Inteiro,Barra da Tijuca,0,15,0,671,738197.0,18117.0,3208.0,1100.14,Apartamento
19256,Apartamento,Freguesia (Jacarepaguá),2,2,1,150,550000.0,850.0,150.0,3666.67,Apartamento
21024,Apartamento,Recreio dos Bandeirantes,3,2,1,167,1250000.0,1186.0,320.0,7485.03,Apartamento
22881,Conjunto Comercial/Sala,Barra da Tijuca,0,1,0,45,550000.0,880.0,1446.0,12222.22,Apartamento
23440,Conjunto Comercial/Sala,Centro,0,0,0,11216,874895.0,196291.0,NaN,78.00,Apartamento
23491,Apartamento,Botafogo,4,1,1,300,4500000.0,1100.0,NaN,15000.00,Apartamento
25119,Prédio Inteiro,Centro,0,0,0,7000,560000.0,NaN,NaN,80.00,Apartamento
25632,Prédio Inteiro,Humaitá,0,96,0,8279,1324640.0,165580.0,96889.0,160.00,Apartamento
25775,Prédio Inteiro,Centro,0,0,0,9200,950000.0,NaN,45508.0,103.26,Apartamento
26327,Conjunto Comercial/Sala,Caju,0,0,0,10660,1279200.0,NaN,NaN,120.00,Apartamento
26552,Prédio Inteiro,Barra da Tijuca,0,99,0,8467,677360.0,194741.0,59269.0,80.00,Apartamento
28011,Prédio Inteiro,Gamboa,0,89,0,9088,772549.0,NaN,16733.0,85.01,Apartamento
28047,Prédio Inteiro,Humaitá,0,96,0,8279,1076270.0,NaN,NaN,130.00,Apartamento
30493,Conjunto Comercial/Sala,Botafogo,0,42,0,4530,679500.0,152706.0,20926.0,150.00,Apartamento
30690,Conjunto Comercial/Sala,Ipanema,0,1,0,30,800000.0,1700.0,258.0,26666.67,Apartamento

In [45]:
valor = dados['Valor']

In [46]:
Q1 = valor.quantile(.25)
Q3 = valor.quantile(.75)
IIQ = Q3 - Q1
limite_inferior = Q1 - 1.5 * IIQ
limite_superior = Q3 + 1.5 * IIQ

In [47]:
selecao = (valor >= limite_inferior) & (valor <= limite_superior)
dados_new = dados[selecao]

In [49]:
dados_new.boxplot(['Valor'])

In [50]:
dados.hist(['Valor'])
dados_new.hist(['Valor'])

array([[<AxesSubplot:title={'center':'Valor'}>]], dtype=object)

In [51]:
## exercicio
## Nosso objetivo neste exercício é obter o conjunto de estatísticas representado na figura acima. 
## Para isso, baixe aqui o arquivo aluguel_amostra.csv, e utilize-o para realizar suas análises utilizando 
## como variável alvo o Valor m2 (valor do metro quadrado). 
## Lembrando que Q1 representa o 1º quartil e Q3 o 3º quartil, 
## selecione o item com a resposta correta (considere somente duas casas decimais):

In [56]:
dados_ex = pd.read_csv('dados/aluguel_amostra.csv', sep = ';')

In [54]:
valor_m2_ex = dados_ex['Valor m2']

In [57]:
dados_ex.head(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor m2,Tipo Agregado
0,Apartamento,Recreio dos Bandeirantes,3,2,1,320,3200.0,1319.0,0.0,10.00,Apartamento
1,Apartamento,Maracanã,2,0,0,59,800.0,725.0,47.0,13.56,Apartamento
2,Apartamento,Leblon,3,2,1,147,7500.0,1000.0,381.0,51.02,Apartamento
3,Apartamento,São Conrado,3,3,3,270,14999.0,2800.0,1200.0,55.55,Apartamento
4,Apartamento,Tijuca,2,1,0,65,1200.0,640.0,97.0,18.46,Apartamento
5,Apartamento,Cachambi,2,1,1,75,1400.0,715.0,0.0,18.67,Apartamento
6,Apartamento,Glória,1,0,0,52,1700.0,560.0,0.0,32.69,Apartamento
7,Apartamento,Engenho Novo,2,1,0,70,1200.0,430.0,21.0,17.14,Apartamento
8,Apartamento,Maracanã,1,1,0,59,1500.0,410.0,0.0,25.42,Apartamento
9,Apartamento,Flamengo,3,0,0,100,2500.0,980.0,105.0,25.00,Apartamento

In [58]:
Q1 = valor_m2_ex.quantile(.25)
Q3 = valor_m2_ex.quantile(.75)
IIQ = Q3 - Q1
limite_inferior = Q1 - 1.5 * IIQ
limite_superior = Q3 + 1.5 * IIQ

In [63]:
limite_inferior

-10.340000000000003

In [64]:
selecao_ex = (valor_m2_ex >= limite_inferior) & (valor_m2_ex <= limite_superior)
dados_new = dados[selecao]

In [66]:
dados_ex.boxplot(['Valor m2'])